var annotated_dup =
[
    [ "sc", null, [
      [ "timer", null, [
        [ "TimedInterface", "classsc_1_1timer_1_1_timed_interface.html", "classsc_1_1timer_1_1_timed_interface" ],
        [ "TimerServiceInterface", "classsc_1_1timer_1_1_timer_service_interface.html", "classsc_1_1timer_1_1_timer_service_interface" ]
      ] ],
      [ "EventDrivenInterface", "classsc_1_1_event_driven_interface.html", "classsc_1_1_event_driven_interface" ],
      [ "StatemachineInterface", "classsc_1_1_statemachine_interface.html", "classsc_1_1_statemachine_interface" ]
    ] ],
    [ "statechart_events", null, [
      [ "SctEvent", "classstatechart__events_1_1_sct_event.html", null ],
      [ "SctEvent__add_step", "classstatechart__events_1_1_sct_event____add__step.html", null ],
      [ "SctEvent__custom_setup", "classstatechart__events_1_1_sct_event____custom__setup.html", null ],
      [ "SctEvent__exit_process", "classstatechart__events_1_1_sct_event____exit__process.html", null ],
      [ "SctEvent__finish_process", "classstatechart__events_1_1_sct_event____finish__process.html", null ],
      [ "SctEvent__finish_process_idle", "classstatechart__events_1_1_sct_event____finish__process__idle.html", null ],
      [ "SctEvent__finished_process", "classstatechart__events_1_1_sct_event____finished__process.html", null ],
      [ "SctEvent__go_to_loop", "classstatechart__events_1_1_sct_event____go__to__loop.html", null ],
      [ "SctEvent__go_to_menu", "classstatechart__events_1_1_sct_event____go__to__menu.html", null ],
      [ "SctEvent__heating", "classstatechart__events_1_1_sct_event____heating.html", null ],
      [ "SctEvent__heating_2", "classstatechart__events_1_1_sct_event____heating__2.html", null ],
      [ "SctEvent__idle", "classstatechart__events_1_1_sct_event____idle.html", null ],
      [ "SctEvent__keypad_input_cancel", "classstatechart__events_1_1_sct_event____keypad__input__cancel.html", null ],
      [ "SctEvent__keypad_input_confirm", "classstatechart__events_1_1_sct_event____keypad__input__confirm.html", null ],
      [ "SctEvent__loop_finished", "classstatechart__events_1_1_sct_event____loop__finished.html", null ],
      [ "SctEvent__menu", "classstatechart__events_1_1_sct_event____menu.html", null ],
      [ "SctEvent__recipe_1", "classstatechart__events_1_1_sct_event____recipe__1.html", null ],
      [ "SctEvent__recipe_1_process", "classstatechart__events_1_1_sct_event____recipe__1__process.html", null ],
      [ "SctEvent__recipe_2", "classstatechart__events_1_1_sct_event____recipe__2.html", null ],
      [ "SctEvent__recipe_2_process", "classstatechart__events_1_1_sct_event____recipe__2__process.html", null ],
      [ "SctEvent__recipe_3", "classstatechart__events_1_1_sct_event____recipe__3.html", null ],
      [ "SctEvent__recipe_3_process", "classstatechart__events_1_1_sct_event____recipe__3__process.html", null ],
      [ "SctEvent__recipe_4", "classstatechart__events_1_1_sct_event____recipe__4.html", null ],
      [ "SctEvent__recipe_4_process", "classstatechart__events_1_1_sct_event____recipe__4__process.html", null ],
      [ "SctEvent__recipe_5", "classstatechart__events_1_1_sct_event____recipe__5.html", null ],
      [ "SctEvent__recipe_5_process", "classstatechart__events_1_1_sct_event____recipe__5__process.html", null ],
      [ "SctEvent__recipe_back_menu", "classstatechart__events_1_1_sct_event____recipe__back__menu.html", null ],
      [ "SctEvent__resting", "classstatechart__events_1_1_sct_event____resting.html", null ],
      [ "SctEvent__resting_2", "classstatechart__events_1_1_sct_event____resting__2.html", null ],
      [ "SctEvent__set_temperature", "classstatechart__events_1_1_sct_event____set__temperature.html", null ],
      [ "SctEvent__set_temperature_2", "classstatechart__events_1_1_sct_event____set__temperature__2.html", null ],
      [ "SctEvent__set_time", "classstatechart__events_1_1_sct_event____set__time.html", null ],
      [ "SctEvent__set_time_2", "classstatechart__events_1_1_sct_event____set__time__2.html", null ],
      [ "SctEvent__standard_process", "classstatechart__events_1_1_sct_event____standard__process.html", null ],
      [ "SctEvent__standard_process_custom", "classstatechart__events_1_1_sct_event____standard__process__custom.html", null ],
      [ "SctEvent__start_button", "classstatechart__events_1_1_sct_event____start__button.html", null ],
      [ "SctEvent__start_first_step", "classstatechart__events_1_1_sct_event____start__first__step.html", null ],
      [ "SctEvent__start_recipe_custom", "classstatechart__events_1_1_sct_event____start__recipe__custom.html", null ],
      [ "SctEvent__step_finished", "classstatechart__events_1_1_sct_event____step__finished.html", null ],
      [ "SctEvent__temp_finished", "classstatechart__events_1_1_sct_event____temp__finished.html", null ],
      [ "TimedSctEvent", "classstatechart__events_1_1_timed_sct_event.html", null ],
      [ "TypedSctEvent", "classstatechart__events_1_1_typed_sct_event.html", null ]
    ] ],
    [ "ControlCommand", "struct_control_command.html", "struct_control_command" ],
    [ "DisplayCommand", "struct_display_command.html", "struct_display_command" ],
    [ "Recipe", "struct_recipe.html", "struct_recipe" ],
    [ "RecipeStep", "struct_recipe_step.html", "struct_recipe_step" ],
    [ "Statechart", "class_statechart.html", "class_statechart" ],
    [ "StatechartCallback", "class_statechart_callback.html", "class_statechart_callback" ],
    [ "StatechartTimer", "class_statechart_timer.html", "class_statechart_timer" ],
    [ "TemperatureData", "struct_temperature_data.html", null ]
];